<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/research/index/pid/<?=$this->pid?>" class="list-group-item">
          <h4 class="list-group-item-heading"><?=$this->projectName->name?></h4>
          <p class="list-group-item-text">Gerencie aqui os dados da pesquisa</p>
        </a>
        <a href="/research/new/pid/<?=$this->pid?>" class="list-group-item"><i class="fa fa-pencil"></i> Novo</a>
        <a href="/research/view/pid/<?=$this->pid?>" class="list-group-item"><i class="fa fa-search"></i> Pesquisar</a>
        <a href="#" class="list-group-item active"> Erro gerado</a>
        <a href="/research/report/pid/<?=$this->pid?>" class="list-group-item"><i class="fa fa-list-alt"></i> Relatórios</a>
      </div>
    </div>
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li><a href="/research/index/pid/<?=$this->pid?>"><?=$this->projectName->name?></a></li>
        <li><a href="/research/report/pid/<?=$this->pid?>">Relatórios</a></li>
        <li><a href="/research/error-report/pid/<?=$this->pid?>">Relatório de erros</a></li>
        <li class="active">Erro gerado</li>
      </ol>  
      <div class="page-header">
        <h1>Você gerou um novo erro com sua alteração</h1>
        <hr>
        <div class="col-sm-13">
            <?
            if(is_object($this->list) && !isset($this->list->card_cod)){
              $x=0;
              $y=0;
              foreach($this->list as $body){
                $dt = explode(" ",$body->date_time);
                $date_time = $dt[0];

                if($x==0){
                  $cod_before = $body->card_cod;?>
                  <table class="table table-hover table-bordered">
                  <thead>
                    <th>Cod. do cartão</th>
                    <th>Linha</th>
                    <th>Emb./Desemb.</th>
                    <th>Data</th>
                    <th>Hora</th>
                    <th>Tempo viagem</th>
                  </thead>
                  <tbody>
                  <tr>
                    <td><?=$body->card_cod?></td>
                    <td><?=$body->selected_line?></td>
                    <td><?=$body->e_d?></td>
                    <td><?=Application_Model_General::dateToBr($date_time)?></td>
                    <td><?=$body->hour?></td>
                    <?if($y % 2 == 0){
                      $hour_before = $body->hour;
                      echo "<td>-</td>";
                    }
                    else{
                      $time = Application_Model_General::convertToMinute($body->hour) - Application_Model_General::convertToMinute($hour_before);
                      echo"<td>".$time."min</td>";
                    }?>
                  </tr>
              <?}
                else{
                  if($cod_before == $body->card_cod){?>
                    <tr>
                    <td><?=$body->card_cod?></td>
                    <td><?=$body->selected_line?></td>
                    <td><?=$body->e_d?></td>
                    <td><?=Application_Model_General::dateToBr($date_time)?></td>
                    <td><?=$body->hour?></td>
                    <?if($y % 2 == 0){
                      $hour_before = $body->hour;
                      echo "<td>-</td>";
                    }
                    else{
                      $time = Application_Model_General::convertToMinute($body->hour) - Application_Model_General::convertToMinute($hour_before);
                      echo"<td>".$time."min</td>";
                    }?>
                    </tr>
                <?}
                }
                $cod_before = $body->card_cod;
                $x++;
                $y++;
              }
            }?>
            <tr>
            <td colspan="7">
            <?if($this->mi != 1){?>
            <a class="btn btn-default btn-sm help" data-toggle="modal" title="Aceitar erro" data-target="#accept_<?=$body->id?>"><i class="fa fa-thumbs-up"></i></a>
            <?}?>
            <a class="btn btn-default btn-sm help" data-toggle="modal" title="NÃO aceitar erro" data-target="#deny_<?=$body->id?>"><i class="fa fa-thumbs-down"></i></a>
            </td>
            </tr>
          </tbody>
        </table>
        </div>
      </div>
     </div>
    </div>
  </div>


<?if(count($this->list)){
foreach($this->list as $body){?>
<form method="post" class="form-horizontal" action="/research/accept-new-error/pid/<?=$this->pid?>" enctype="multipart/form-data">
  <div class="modal fade" id="accept_<?=$body->id?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Aceitar erro do registro</h4>
        </div>
        <div class="modal-body">
             <p>Tem certeza que deseja aceitar o erro deste registro? Desta forma ele não aparecerá mais neste relatório.</p>
        </div>  
        <div class="modal-footer">
            <input type="hidden" value="<?=$body->id?>" name="id">
            <input type="hidden" value="<?=$body->card_cod?>" name="card_cod">
            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            <button type="submit" class="btn btn-danger">Aceitar</button>
        </div>
      </div> 
    </div>
  </div>       
  </form>

    <form method="post" class="form-horizontal" action="/research/deny-new-error/pid/<?=$this->pid?>" enctype="multipart/form-data">
  <div class="modal fade" id="deny_<?=$body->id?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">NÃO aceitar o erro</h4>
        </div>
        <div class="modal-body">
             <p>Tem certeza que deseja não aceitar o erro, você será redirecionado para o relatório de possíveis erros.</p>
        </div>  
        <div class="modal-footer">
            <input type="hidden" value="<?=$body->id?>" name="id">
            <input type="hidden" value="<?=$body->card_cod?>" name="card_cod">
            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            <button type="submit" class="btn btn-danger">Ok!</button>
        </div>
      </div> 
    </div>
  </div>       
  </form>

  
<?}
}?>