<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/research/index/pid/<?=$this->pid?>" class="list-group-item">
          <h4 class="list-group-item-heading"><?=$this->projectName->name?></h4>
          <p class="list-group-item-text">Gerencie aqui os dados das linhas</p>
        </a>
        <a href="/research/new/pid/<?=$this->pid?>" class="list-group-item"><i class="fa fa-pencil"></i> Nova Linha</a>
        <a href="/research/view/pid/<?=$this->pid?>" class="list-group-item"><i class="fa fa-search"></i> Pesquisar </a>
      </div>
    </div>
    <div class="col-md-9">
     <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li><a href="/research/index/pid/<?=$this->pid?>"><?=$this->projectName->name?></a></li>
        <li class="active">Linhas</li>
      </ol>   
      <div class="jumbotron">
        <h1><?=$this->projectName->name?></h1>
        <p class="lead">Neste módulo você poderá cadastrar linhas, pontos de controle, cercas.</p>
      </div>
     </div>
    </div>
  </div>