<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/research/index/pid/<?=$this->pid?>" class="list-group-item">
          <h4 class="list-group-item-heading"><?=$this->projectName->name?></h4>
        </a>
        <a href="/research/manager/pid/<?=$this->pid?>" class="list-group-item"><i class="fa fa-gears"></i> Gerenciar</a>
        <a href="/research/buslines/pid/<?=$this->pid?>" class="list-group-item"><i class="fa fa-random"></i> Linhas</a>
      </div>
    </div>
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li class="active"><?=$this->projectName->name?></li>
      </ol>  
      <div class="jumbotron">
        <h1><?=$this->projectName->name?></h1>
        <p class="lead">Neste módulo você poderá gerenciar os dados coletados na pesquisa ou inserir os dados principais para a pesquisa.</p>
      </div>
     </div>
    </div>
  </div>