<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/research/manager/pid/<?=$this->pid?>" class="list-group-item">
          <h4 class="list-group-item-heading"><?=$this->projectName->name?></h4>
          <p class="list-group-item-text">Gerencie aqui os dados da pesquisa</p>
        </a>
        <a href="/research/new/pid/<?=$this->pid?>" class="list-group-item active"><i class="fa fa-pencil"></i> Novo</a>
        <a href="/research/view/pid/<?=$this->pid?>" class="list-group-item"><i class="fa fa-search"></i> Pesquisar</a>
        <a href="/research/report/pid/<?=$this->pid?>" class="list-group-item"><i class="fa fa-list-alt"></i> Relatórios</a>
      </div>
    </div>
    <div class="col-md-9">
      <ol class="breadcrumb">
        <li><a href="/dashboard">Página inicial</a></li>
        <li><a href="/research/index/pid/<?=$this->pid?>"><?=$this->projectName->name?></a></li>
        <li class="active">Novo</li>
      </ol>  
      <div class="page-header">
        <h1>Upload<small> faça upload dos arquivos da pesquisa</small></h1>
        <hr>
        <?if($this->success){?>
          <div class="well well-lg">
            <span class="glyphicon glyphicon-thumbs-up"></span> Arquivo inserido corretamente no sistema.<br>
          </div>
        <?}else{?>
        <form enctype="multipart/form-data" class="form-horizontal" method="post" action="/research/new/pid/<?=$this->pid?>" id='formGpsData' name='formGpsData'>
          <div class="form-group"><label for="start_date" class="col-lg-2 control-label required">Arquivo dados GPS</label>
            <div class="col-lg-5">
            <input type="file" name="gpsData_file" id="gpsData_file"></div>
          </div>
          <div class="form-group"><div class="col-lg-5">
            <input type="submit" name="submit" id="submitGpsData" value="Enviar" class="col-lg-offset-5 btn btn-primary"></div>
          </div>
        </form>
        <br><hr><br><br>
        <form enctype="multipart/form-data" class="form-horizontal" method="post" action="/research/new/pid/<?=$this->pid?>" id='formResearchData' name='formResearchData'>
          <div class="form-group"><label for="start_date" class="col-lg-2 control-label required">Arquivo dados pesquisa</label>
            <div class="col-lg-5">
            <input type="file" name="researchData_file" id="researchData_file"></div>
          </div>
          <div class="form-group"><div class="col-lg-5">
            <input type="submit" name="submit" id="submitResearchData" value="Enviar" class="col-lg-offset-5 btn btn-primary"></div>
          </div>
        </form>
        <?}?>
        <div id="barProgressMCO" style='margin-left: 80px; display: none'>
          <img src='/img/loading.gif' id='loading' style='margin-left: 70px;'> <br><br>
          <p>Lendo e importando os dados</p>
          <p style='margin-left: 40px;'>Por favor aguarde...</p>
        </div>
      </div>
     </div>
    </div>
  </div>