
<!DOCTYPE html>
<html lang="pt_BR">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Gerenciamento de pesquisa de embarque e desembarque">
    <meta name="author" content="IMTT">

    <title>Pesquisa ED</title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/justified-nav.css" rel="stylesheet">

  </head>

  <body>

    <div class="container">

      <div class="masthead">
        <img width="200" height="200" src='/img/tecbus.png' class="img-responsive">
      </div>
      <!-- Jumbotron -->
      <div class="jumbotron">
        <h1>Pesquisa sobe e desce</h1>
        <p class="lead">Gerenciamento de pesquisa de embarque e desembarque.</p>
        <p><a class="btn btn-lg btn-success" href="auth/login">Entrar</a></p>
      </div>

    </div> <!-- /container -->

  </body>
</html>
