<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <a href="/dashboard" class="list-group-item">
          <h4 class="list-group-item-heading">Página inicial</h4>
            <p class="list-group-item-text">Pesquisa ED</p>
        </a>
        <?if(is_object($this->list) && !isset($this->list->name)){
              foreach($this->list as $body){?>
                <a href="/research/index/pid/<?=$body->id?>" class="list-group-item"><?=$body->name?></a>
            <?}
          }?>
      </div>
    </div>
    <div class="col-md-9">
    	<ol class="breadcrumb">
        <li class="active">Página inicial</li>
      </ol>
      <div class="text-center">
        <br><br><br>
		    <img src='/img/codigodebarra.jpg' class="img-responsive img-thumbnail"><br><br>
		  </div>
		 </div>
		</div>
	</div>
